apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dtrack-db-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-homelab
    kind: ClusterSecretStore
  target:
    name: dtrack-db-credentials
    creationPolicy: Owner
    template:
      data:
        username: dtrack
        password: "{{ .password }}"
  data:
    - secretKey: password
      remoteRef:
        key: dtrack-db-password
