apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: dtrack-api-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: dtrack-api-key
    creationPolicy: Owner
    template:
      data:
        api-key: "{{ .apiKey }}"
  data:
    - secretKey: apiKey
      remoteRef:
        key: cluster/dtrack
        property: api_key
